### PR TITLE
1st draft

### PR DESCRIPTION
**Pull request by jrrbru**
1st draft of post for 3/23. Note that I have the wrong date on the file, so I could test locally.

### CODE REVIEW

**Comment by laurawhalin** [comment]
This looks ready to go! If you want to update the date to tomorrow, I'll go ahead and merge this. Thanks Jason!

**Comment by laurawhalin** [comment]
I took care of the dates and added padding to the images.

**Comment by jrrbru** [comment]
Thanks, Laura, I apologize for not getting to this. I've been heads-down in some crazy code over here, and it slipped my mind.

**Comment by laurawhalin** [comment]
It's is no big deal at all! I realize the blog isn't everyone's highest
priority...so thank you very much for fitting it in!

**Pull request merged**
